
[template_input_parameters.project]
template_value = "#{project}#"
condition = "\\b[a-zA-Z]+\\b"
description = "Project Name"

[template_input_parameters.region]
template_value = "#{region}#"
condition = "^[a-z]{2}-[a-z]{4,10}-\\d$"
description = "Aws Region"

[template_input_parameters.backend_region]
template_value = "#{backend_region}#"
condition = "^[a-z]{2}-[a-z]{4,10}-\\d$"
description = "Backend Aws Region"

[template_input_parameters.backend_bucket]
template_value = "#{backend_bucket}#"
condition = "^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$"
description = "Backend Bucket"

[template_input_parameters.owner]
template_value = "#{owner}#"
condition = "\\b[a-zA-Z]+\\b"
description = "Deployment Owner"

[template_input_parameters.client]
template_value = "#{client}#"
condition = "\\b[a-zA-Z]+\\b"
description = "Client or Area for this deployment"

[template_input_parameters.backend_dynamodb]
template_value = "#{backend_dynamodb}#"
condition = "^[a-zA-Z0-9_.-]{3,255}$"
description = "Dynamodb for lock state"

[template_input_parameters.environment]
template_value = "#{environment}#"
condition = "(dev|qa|stg|test|prod)"
description = "Environment allowed values (dev|qa|stg|test|prod)"


[template_input_parameters.deployment_profile]
template_value = "#{deployment_profile}#"
condition = "^[a-zA-Z0-9_.-]{3,255}$"
description = "Deployment profile aws cli"

[template_input_parameters.backend_profile]
template_value = "#{backend_profile}#"
condition = "^[a-zA-Z0-9_.-]{3,255}$"
description = "Backend profile for s3 remote state"




[project_properties]
project = "blueprint-devsecops-ecs-ado"
region = "us-east-1"
backend_region = "us-east-1"
backend_bucket = "blueprint-devsecops-cluster-prd-terraform-remote-tfstate"
owner = "DevSecOps"
client = "Bancolombia"
backend_dynamodb = "blueprint-devsecops-cluster-prd-terraform-db-lock"
environment = "dev"
deployment_profile = "sh-tm-bco"
backend_profile = "sh-tm-bco"
[iacpb]
project_id = "blueprint-devsecops-ecs-azure-devops"
